---
title: "dm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ClinAD)
```

```{r}
#' @describeIn accessor select a variable with the dollar symbol `$`.
#' @include domain.R
#'
setMethod(
  "$",
  signature(x = "Domain"),
  function(x, name) {
    x@df <- x@df[, name, drop = FALSE]
    x@columns <- columns[name, seq_len(ncol(columns)), drop = FALSE]
    validObject(x)
    x
  }
)


#' @describeIn accessor assign a variable with the dollar symbol `$`.
#' @include domain.R
#'
setMethod(
  "$<-",
  signature(x = "Domain"),
  function(x, name, value) {
    if (is(value, "Domain")) {
      x@df[, name] <- value@df
      x@columns <- expand_columns(x@columns, value@columns)
    } else {
      x@df[, name] <- value
    }
    x
  }
)


expand_columns <- function(x, y) {

  new_y <- setdiff(colnames(x), colnames(y))
  new_x <- setdiff(colnames(y), colnames(x))
  fill_na <- function(x, data) rep(NA, nrow(data))

  if (length(new_x) > 0) {
    new_x <- lapply(
      setNames(nm = new_x),
      fill_na,
      data = x
    )

    x <- cbind(x, new_x)
  }

  if (length(new_y) > 0) {
    new_y <- lapply(
      setNames(nm = new_y),
      fill_na,
      data = y
    )

    y <- cbind(new_y, y)
  }

  rbind(x, y)

}
t1 <- data.frame(
  row.names = "STUDYID", label = "Study Identifier", names = "name"
)
t2 <- data.frame(
  row.names = c("SUBJID", "AGE"),
  names = c("Subject Identifier", "Age")
)

expand_columns(t1, t2)
dta_1 <- DM(
  dm[1:3, c("STUDYID", "SUBJID", "ARMCD")],
  data.frame(row.names = "STUDYID", label = "Study Identifier")
)

dta_2 <- DM(
  dm[1:3, c("STUDYID", "SUBJID", "AGE")],
  data.frame(
    row.names = c("STUDYID", "AGE"),
    names = c("Study Identifier", "Age")
  )
)


dta_1
dta_2
# dta_1$AGE <- dta_2$AGE # nolint
expand_columns(dta_1@columns, (dta_2$AGE)@columns)
dta_1

```

